name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['24.14']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v4 # Extracts pnpm version from package.json packageManager field

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'

      - name: Check for known security issues
        run: pnpm audit

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm fmt:check

      - name: Types
        run: pnpm types

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Test
        run: pnpm coverage

      - name: Build
        run: pnpm build

      - name: Build Examples
        run: cd examples && pnpm build
