name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Remark
        run: pnpm remark

      - name: Prettier
        run: pnpm prettier

      - name: Types
        run: pnpm types

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Test
        run: pnpm coverage

      - name: Build
        run: pnpm build
